version: '1'
services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock

    client:
        image: 'maximillllian/review-app:latest'
        container_name: 'review-app'
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - VIRTUAL_PORT=8080
            - VIRTUAL_HOST=dev.localhost
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/app
            - /app/node_modules
