name: Manually deploy
on:
    push:
        branches:
            - step3-reusable-workflows
    workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      container_name: review-app-${{ github.ref_name }}
    secrets: 
        HOST_ADDRESS: ${{ github.ref_name }}.${{ secrets.ARTIFACT_HOST }},www.${{ github.ref_name }}.${{ secrets.ARTIFACT_HOST }}
        USER: ${{ secrets.USER }}
        PSWD: ${{ secrets.PSWD }}
        HOST: ${{ secrets.HOST }}
        ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}       
